### ISSUE TITLE
Use fuzzy search to filter files

### ISSUE THREAD

**Issue by vincentkosciuszko** [parnic/VSQuickOpenFile#12]
I haven't looked at the source yet but from using the extension it feels like only the name of the file is used to filter the list of files and not the whole path. Would be cool to have something better to filter the list.

**Comment by parnic** [comment]
If you click the Settings checkbox, there is an option to search the whole path.

**Comment by vincentkosciuszko** [comment]
Yes but you have to write the full path. 

Let's say i've a file `index.cshtml` inside a `View/Category` directory I can't just do `CatIn` to find the file. 

And that's what fuzzy search do.

**Comment by parnic** [comment]
You can type `Cat In` to find the file, though. Spaces are wildcards and each term is not order-dependent. I'd be happy to accept a PR adding the style of search you're requesting, though! :)

**Comment by vincentkosciuszko** [comment]
This work but sadly the settings go away every time you open a file. Is that the expected behavior? 

I'll look at the source code. I've never took a look at how VS's extensions work.

**Comment by parnic** [comment]
The toggle is intended to be a per-search setting, yes. It would be simple to make it persist if people would prefer it behave that way.
