### ISSUE TITLE
fail to use after updated to 17.9.6 (Visual Studio 2022)

### ISSUE THREAD

**Issue by wai3aa1sam** [parnic/VSQuickOpenFile#14]
down-grading to previous version could use, while updated to new version (17.9.6) failed to use (cannot open the "Quick File Open" window). Will there be any update on that? Thanks.

**Comment by parnic** [comment]
It's working for me in 17.9.6. If you have any more information about a specific environment that is causing problems or log files or anything, I'd be happy to take a look. As of now, I can't reproduce the issue.

**Comment by wai3aa1sam** [comment]
Sorry for the late reply, seems that my shortcut key setting is conflict with Visual Studio updated key bindings. Since I could open the "Quick File Open" window manually in the tool bar (just found it). I close the issue now. Sorry for the false alarm. Thank you for your time.
