### ISSUE TITLE
Trying to open txt file causes error and crash

### ISSUE THREAD

**Issue by MartinL0815** [parnic/VSQuickOpenFile#6]
I wanted to open a txt file, typed in the name and pressed enter.

The result was:

>
![error message trying to open a txt file](https://user-images.githubusercontent.com/525700/57682418-18524d00-7632-11e9-91d8-accbc9cabb2c.png)

Pressing enter a second time caused a crash and VS2019 restarted.

**Comment by parnic** [comment]
Hmm, I'm not having this issue. I added a txt file to my project and opened it with the extension. If you find any other information about what's required to reproduce this problem, please let me know.

**Comment by parnic** [comment]
Ah, looks like it happens if a text file is added to the solution (as opposed to the project). I'll see what I can do here.

**Comment by parnic** [comment]
I'm at a bit of a loss on this one. The item in question is a ProjectItem like any other, but calling Open() on it causes it to throw the pictured NotImplementedException. I don't know why that would be or how to call Open on these items.

**Comment by parnic** [comment]
Got it.
