### ISSUE TITLE
Visual Studio 2022

### ISSUE THREAD

**Issue by JRosanowski** [parnic/VSQuickOpenFile#9]
Are there any plans to support VS 2022?

Thanks

**Comment by parnic** [comment]
I'd love to. I've tried to update it a few times, but there are fundamental changes that make it difficult. Hopefully I can find some time to do it soon!

**Comment by JRosanowski** [comment]
Great. Thanks for the extension, I use it everyday.

**Comment by parnic** [comment]
I have a version that can produce a 2022 VSIX at this branch:

https://github.com/parnic/VSQuickOpenFile/tree/vs2022

There's a lot of work left to do, and Microsoft didn't make this easy, but hopefully I'll be able to clean this up soon.

**Comment by vincentkosciuszko** [comment]
@parnic I see you haven't updated the extension for more than a year. Did you lose interest?

**Comment by parnic** [comment]
> @parnic I see you haven't updated the extension for more than a year. Did you lose interest? 

No, there is a branch for 2022 support and a pre release on GitHub with the vsix. It's published on the marketplace. I'll get it merged into main soon.
